# Generated by Django 5.0.4 on 2024-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_recurrentdeposit_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="currenttransaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="savingstransaction",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
