# Generated by Django 5.0.4 on 2024-04-30 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("Personal Loan", "Personal Loan"),
                            ("Home Loan", "Home Loan"),
                            ("Car Loan", "Car Loan"),
                            ("Education Loan", "Education Loan"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("Personal Loan", "Personal Loan"),
                            ("Home Loan", "Home Loan"),
                            ("Car Loan", "Car Loan"),
                            ("Education Loan", "Education Loan"),
                        ],
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("duration_months", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("applied_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("approved_date", models.DateField(auto_now_add=True)),
                (
                    "loan_application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loans.loanapplication",
                    ),
                ),
            ],
        ),
    ]
