# Generated by Django 5.0.4 on 2024-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanapproval",
            name="interest_rate",
        ),
        migrations.AddField(
            model_name="loanapproval",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Approved",
                max_length=20,
            ),
        ),
    ]
