# Generated by Django 5.0.4 on 2024-05-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_remove_loanapproval_interest_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapproval",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
